// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jsperandio/goexptCloudRun/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewLocationFinder creates a new instance of LocationFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocationFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocationFinder {
	mock := &LocationFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LocationFinder is an autogenerated mock type for the LocationFinder type
type LocationFinder struct {
	mock.Mock
}

type LocationFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *LocationFinder) EXPECT() *LocationFinder_Expecter {
	return &LocationFinder_Expecter{mock: &_m.Mock}
}

// FindByZipcode provides a mock function for the type LocationFinder
func (_mock *LocationFinder) FindByZipcode(ctx context.Context, zipcode string) (entity.Location, error) {
	ret := _mock.Called(ctx, zipcode)

	if len(ret) == 0 {
		panic("no return value specified for FindByZipcode")
	}

	var r0 entity.Location
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.Location, error)); ok {
		return returnFunc(ctx, zipcode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.Location); ok {
		r0 = returnFunc(ctx, zipcode)
	} else {
		r0 = ret.Get(0).(entity.Location)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, zipcode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LocationFinder_FindByZipcode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByZipcode'
type LocationFinder_FindByZipcode_Call struct {
	*mock.Call
}

// FindByZipcode is a helper method to define mock.On call
//   - ctx context.Context
//   - zipcode string
func (_e *LocationFinder_Expecter) FindByZipcode(ctx any, zipcode any) *LocationFinder_FindByZipcode_Call {
	return &LocationFinder_FindByZipcode_Call{Call: _e.mock.On("FindByZipcode", ctx, zipcode)}
}

func (_c *LocationFinder_FindByZipcode_Call) Run(run func(ctx context.Context, zipcode string)) *LocationFinder_FindByZipcode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LocationFinder_FindByZipcode_Call) Return(location entity.Location, err error) *LocationFinder_FindByZipcode_Call {
	_c.Call.Return(location, err)
	return _c
}

func (_c *LocationFinder_FindByZipcode_Call) RunAndReturn(run func(ctx context.Context, zipcode string) (entity.Location, error)) *LocationFinder_FindByZipcode_Call {
	_c.Call.Return(run)
	return _c
}
