// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jsperandio/goexptCloudRun/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewWeatherProvider creates a new instance of WeatherProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeatherProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeatherProvider {
	mock := &WeatherProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WeatherProvider is an autogenerated mock type for the WeatherProvider type
type WeatherProvider struct {
	mock.Mock
}

type WeatherProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *WeatherProvider) EXPECT() *WeatherProvider_Expecter {
	return &WeatherProvider_Expecter{mock: &_m.Mock}
}

// CurrentByLocation provides a mock function for the type WeatherProvider
func (_mock *WeatherProvider) CurrentByLocation(ctx context.Context, lc entity.Location) (entity.Temperature, error) {
	ret := _mock.Called(ctx, lc)

	if len(ret) == 0 {
		panic("no return value specified for CurrentByLocation")
	}

	var r0 entity.Temperature
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Location) (entity.Temperature, error)); ok {
		return returnFunc(ctx, lc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Location) entity.Temperature); ok {
		r0 = returnFunc(ctx, lc)
	} else {
		r0 = ret.Get(0).(entity.Temperature)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Location) error); ok {
		r1 = returnFunc(ctx, lc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WeatherProvider_CurrentByLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentByLocation'
type WeatherProvider_CurrentByLocation_Call struct {
	*mock.Call
}

// CurrentByLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - lc entity.Location
func (_e *WeatherProvider_Expecter) CurrentByLocation(ctx any, lc any) *WeatherProvider_CurrentByLocation_Call {
	return &WeatherProvider_CurrentByLocation_Call{Call: _e.mock.On("CurrentByLocation", ctx, lc)}
}

func (_c *WeatherProvider_CurrentByLocation_Call) Run(run func(ctx context.Context, lc entity.Location)) *WeatherProvider_CurrentByLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Location
		if args[1] != nil {
			arg1 = args[1].(entity.Location)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WeatherProvider_CurrentByLocation_Call) Return(temperature entity.Temperature, err error) *WeatherProvider_CurrentByLocation_Call {
	_c.Call.Return(temperature, err)
	return _c
}

func (_c *WeatherProvider_CurrentByLocation_Call) RunAndReturn(run func(ctx context.Context, lc entity.Location) (entity.Temperature, error)) *WeatherProvider_CurrentByLocation_Call {
	_c.Call.Return(run)
	return _c
}
